# Generated by Django 5.1.7 on 2025-06-04 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_active_date_user_score_user_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_played_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
