# Generated by Django 5.1.7 on 2025-08-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_played_date_user_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
