# Generated by Django 5.1.7 on 2025-06-11 04:12

import word.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='image',
            field=models.ImageField(default='rovoca/default.jpg', upload_to=word.models.wordbook_image_path),
        ),
    ]
