# Generated by Django 5.1.7 on 2025-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_wordbook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
