# Generated by Django 5.1.7 on 2025-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_wordbook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
